### ISSUE TITLE
No docker manifest entry for M3 Max?

### ISSUE THREAD

**Issue by TobiasBg** [coenjacobs/mozart#150]
Hi @coenjacobs,

I'm trying to run mozart via Docker on an M3 Max.
I'm not getting
`no matching manifest for linux/arm64/v8 in the manifest list entries`
when running
`docker pull coenjacobs/mozart`
I didn't see this back in May (when my workflow last used mozart), so that I assume that something changed recently?

Is this something that I can or should adjust in my configuration?

**Comment by TobiasBg** [comment]
Hi again!

Ok, it seems like you have been pushing only `linux/amd64` to Docker Hub [for quite some time](https://github.com/coenjacobs/mozart/commit/8823c51371e431d8c22d210e87b98a1aed25a059), so that my issue probably has a different cause.

It appears that I can simply add `--platform linux/amd64` to the Docker calls to get around this problem.

However, I then get a PHP error from inside the container:
```bash
Fatal error: Uncaught Error: Class "Symfony\Component\Console\Application" not found in /mozart/src/Console/Application.php:8
Stack trace:
#0 /project/vendor/composer/ClassLoader.php(576): include()
#1 /project/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/mozart/vendor/...')
#2 /mozart/bin/mozart(27): Composer\Autoload\ClassLoader->loadClass('CoenJacobs\\Moza...')
#3 /mozart/bin/mozart(29): {closure}('0.8.0')
#4 {main}
  thrown in /mozart/src/Console/Application.php on line 8
```

**Comment by coenjacobs** [comment]
@TobiasBg What tag of the Docker image are you getting that error with?

**Comment by TobiasBg** [comment]
Hi @coenjacobs!
Thanks for the reply!
I'm not using any tag in particular, so I guess it's `latest`. I just call
`docker run --rm -it -v ${PWD}:/project/ coenjacobs/mozart /mozart/bin/mozart compose`
in a build script.

**Comment by coenjacobs** [comment]
@TobiasBg Could you try it with one of the versioned tags: https://hub.docker.com/r/coenjacobs/mozart/tags - the `latest` tag is effectively the `master` branch and can contain faulty builds. I guess I should actually update the README for this as well, as it doesn't say that there either.

**Comment by TobiasBg** [comment]
@coenjacobs: Thanks! Indeed, Using 0.7.1, i.e. calling
`docker run --rm -it -v ${PWD}:/project/ coenjacobs/mozart:0.7.1 /mozart/bin/mozart compose`
resolves both the Docker and the Symfony error.

Unless you would like to keep this issue as a reminder for a potential readme change, this can be closed.

**Comment by coenjacobs** [comment]
@TobiasBg Thanks for letting me know, glad to hear that resolved your issue. I'll leave it open for now, so I have a reminder to work on the documentation indeed - thanks again!
