### ISSUE TITLE
Guzzle calls function in specific namespace, call not rewritten

### ISSUE THREAD

**Issue by coenjacobs** [coenjacobs/mozart#88]
As reported by @spreeuw in #76 comments:

>Guzzle still doesn't work though, throwing: `Uncaught Error: Call to undefined function MyNamespace\GuzzleHttp\Psr7\stream_for()`

I have a feeling that this `stream_for()` function is a function in the `\GuzzleHttp\Psr7` namespace originally and is then called _from_ that same namespace without using the full FQN of the function, since it's in the same namespace. Currently, Mozart does not replace these function calls, since it is unable to distinguish a global function with a function from a namespace that is then prefixed.

What is odd though, is that the original namespace of the file calling the `stream_for()` function isn't transformed into your prefixed namespace (which would resolve the function being undefined, since they are in the same namespace).

@spreeuw Can you elaborate on the error message, from where this is being called and from what package this originates? I have a feeling that this is coming from excluding a package (and thus not being processed) that is then calling a namespaced function inside a package that is actually processed by Mozart and thus have an FQN mismatch.

Could you also share your full (redact sensitive parts) `composer.json` file so we can experiment with it and hopefully bring this issue to a proper solution?

**Comment by Spreeuw** [comment]
Ok, so the full error:

```
Fatal error: Uncaught Error: Call to undefined function MyNameSpace\Vendor\GuzzleHttp\Psr7\stream_for() in \lib\packages\Kunnu\Dropbox\DropboxFile.php:235 Stack trace:
#0 \lib\packages\Kunnu\Dropbox\DropboxFile.php(191): MyNameSpace\Vendor\Kunnu\Dropbox\DropboxFile->open()
#1 \lib\packages\Kunnu\Dropbox\DropboxFile.php(167): MyNameSpace\Vendor\Kunnu\Dropbox\DropboxFile->getStream()
#2 \lib\packages\Kunnu\Dropbox\Http\RequestBodyStream.php(36): MyNameSpace\Vendor\Kunnu\Dropbox\DropboxFile->getContents()
#3 \lib\packages\Kunnu\Dropbox\DropboxClient.php(199): MyNameSpace\Vendor\Kunnu\Dropbox\Http\RequestBodyStream->getBody()
#4 \lib\packages\ in \lib\packages\Kunnu\Dropbox\DropboxFile.php on line 235
```

Which is referring to this line/package:
https://github.com/kunalvarma05/dropbox-php-sdk/blob/f8ab4d32fb832ea18a20ac8fbba76f675e7a6fff/src/Dropbox/DropboxFile.php#L235

This is not PSR loaded but a function included from the `files` part of composer.json in the `guzzle/psr7` library.
https://github.com/guzzle/psr7/blob/7858757f390bbe4b3d81762a97d6e6e786bb70ad/composer.json#L58-L60

Guzzle seems to have such a `files` declaration in various other packages too:
https://github.com/guzzle/guzzle/blob/34bc199aef77ff1c13f7126c0464f8fa9ee55f9f/composer.json#L63-L65
https://github.com/guzzle/promises/blob/ddfeedfff2a52661429437da0702979f708e6ac6/composer.json#L23

So not actually a namespace issue after all. After I included these files manually, everything seemed to load as required.

I am not sure how to do that the 'proper' way though. If I include them in the `files` section of my own composer autoloader:
```
"files": [
	"lib/packages/GuzzleHttp/Promise/functions_include.php",
	"lib/packages/GuzzleHttp/Psr7/functions_include.php",
	"lib/packages/GuzzleHttp/functions_include.php"
]
```

`mozart compose` will crash because it is unable to find those files (it is yet to move them there).

**Comment by Spreeuw** [comment]
@coenjacobs for clarity I think this should be renamed to something like _composer autoloader not linking to `files` from packages after processing_.

**Comment by noknokcody** [comment]
Any update to this? I'm getting a similar error with json_encode.

**Comment by coenjacobs** [comment]
The `stream_for()` function was defined in `guzzlehttp/psr7`'s `src/functions.php`, registered via the files autoloader in its `composer.json`. At the time this issue was filed, Mozart did not process files autoloader entries at all, so the function definition was never moved or namespaced. When the rest of the package's namespace was prefixed, calls to `stream_for()` within the prefixed namespace would fail because the function didn't exist in that namespace.

On the current master branch (upcoming 1.1.0 release), Mozart fully supports the Composer files autoloader. Functions defined in files entries are now properly moved and have their namespaces rewritten, so they will exist in the prefixed namespace as expected. This will be available starting with the first 1.1.0 pre-release.

**Comment by coenjacobs** [comment]
[Version 1.1.0 is now released](https://github.com/coenjacobs/mozart/releases/tag/1.1.0) and fixes this issue. Should you still find a problem with this release, please [open a new GitHub issue](https://github.com/coenjacobs/mozart/issues) and if it is at all related, refer back to this original issue. Thanks again for the issue report, very much appreciated! 🫶
